require 'packages'
require 'lsp'
require 'keybindings'
require 'telescope-config'
require 'treesitter-config'
require 'lualine-config'
require 'run_file'
require 'whichkey-config'
require 'colorscheme'
require 'toggleterm-config'
-- require 'orgmode_config'
require 'bufferline_config'
-- require 'nvim_tree'
require 'iterm2'
require 'drawer'
--
-- #region
--
require 'git_int_config'
require 'mdeval-config'
require 'format_config'
-- require 'comments'
require 'spell_config'
require 'config'
